repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
      args:
        - --unsafe
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: end-of-file-fixer
    - id: check-symlinks
    - id: check-added-large-files
    - id: detect-private-key
-   repo: github.com/ansible-community/ansible-lint
    rev: v6.15.0
    hooks:
    - id: ansible-lint